//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.10 at 12:13:11 AM CET 
//


package com.tableausoftware.documentation.api.rest.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for valueMatchType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="valueMatchType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="value" type="{http://tableau.com/api}semanticsValueType" minOccurs="0"/>
 *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="valueConcept" type="{http://tableau.com/api}valueConceptType" minOccurs="0"/>
 *         &lt;element name="valueConceptURI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fieldConceptURI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "valueMatchType", propOrder = {
    "value",
    "weight",
    "valueConcept",
    "valueConceptURI",
    "fieldConceptURI"
})
public class ValueMatchType {

    protected SemanticsValueType value;
    protected Double weight;
    protected ValueConceptType valueConcept;
    protected String valueConceptURI;
    protected String fieldConceptURI;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link SemanticsValueType }
     *     
     */
    public SemanticsValueType getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link SemanticsValueType }
     *     
     */
    public void setValue(SemanticsValueType value) {
        this.value = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWeight(Double value) {
        this.weight = value;
    }

    /**
     * Gets the value of the valueConcept property.
     * 
     * @return
     *     possible object is
     *     {@link ValueConceptType }
     *     
     */
    public ValueConceptType getValueConcept() {
        return valueConcept;
    }

    /**
     * Sets the value of the valueConcept property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueConceptType }
     *     
     */
    public void setValueConcept(ValueConceptType value) {
        this.valueConcept = value;
    }

    /**
     * Gets the value of the valueConceptURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueConceptURI() {
        return valueConceptURI;
    }

    /**
     * Sets the value of the valueConceptURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueConceptURI(String value) {
        this.valueConceptURI = value;
    }

    /**
     * Gets the value of the fieldConceptURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldConceptURI() {
        return fieldConceptURI;
    }

    /**
     * Sets the value of the fieldConceptURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldConceptURI(String value) {
        this.fieldConceptURI = value;
    }

}
